/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden2025;

import oru.inf.InfDB;

import java.util.HashMap;
import javax.swing.JOptionPane;


/**
 *
 * @author Ninee
 */
public class hanteraPartner extends javax.swing.JFrame {
    
  private String inloggadAnvandare;
  private boolean isAdmin; 
  private InfDB idb;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(hanteraPartner.class.getName());

    
    public hanteraPartner(InfDB idb, String inloggadAnvandare, boolean isAdmin){
        
    this.idb = idb;
    this.inloggadAnvandare = inloggadAnvandare;
    this.isAdmin = isAdmin;
    
     initComponents();
     
     loadPartnerData();
     
     setFieldsEditable(false);
    
    }
    
    /**
     * Creates new form hanteraPartner
     */
    public hanteraPartner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PartnerID = new javax.swing.JLabel();
        Namn = new javax.swing.JLabel();
        KontaktPerson = new javax.swing.JLabel();
        KontaktEpost = new javax.swing.JLabel();
        Telefon = new javax.swing.JLabel();
        Adress = new javax.swing.JLabel();
        Bransch = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        GåTillbakaKnapp = new javax.swing.JButton();
        Partners = new javax.swing.JComboBox<>();
        btnSpara = new javax.swing.JButton();
        btnÄndraUppgifter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PartnerID.setText("PartnerID");

        Namn.setText("Namn");

        KontaktPerson.setText("Kontaktperson");

        KontaktEpost.setText("Kontaktepost");

        Telefon.setText("Telefon");

        Adress.setText("Adress");

        Bransch.setText("bransch");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField6");

        jTextField7.setText("jTextField7");

        GåTillbakaKnapp.setText("");
        GåTillbakaKnapp.addActionListener(this::GåTillbakaKnappActionPerformed);

        Partners.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Partners.addActionListener(this::PartnersActionPerformed);

        btnSpara.setText("Spara");
        btnSpara.addActionListener(this::btnSparaActionPerformed);

        btnÄndraUppgifter.setText("Ändra uppgifter");
        btnÄndraUppgifter.addActionListener(this::btnÄndraUppgifterActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Bransch)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Telefon)
                                    .addComponent(Adress)))
                            .addGap(137, 137, 137)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(jTextField6)
                                .addComponent(jTextField7)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(KontaktEpost)
                            .addGap(115, 115, 115)
                            .addComponent(jTextField4))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PartnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Namn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(121, 121, 121)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(KontaktPerson)
                            .addGap(109, 109, 109)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Partners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(GåTillbakaKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnÄndraUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSpara))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Partners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GåTillbakaKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PartnerID)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Namn)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KontaktPerson)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KontaktEpost)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefon)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adress)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bransch)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnÄndraUppgifter))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartnersActionPerformed
        // TODO add your handling code here:
        
         try {
        String vald = (String) Partners.getSelectedItem();
        if (vald == null) return;

        String pid = vald.split(" - ")[0];

        HashMap<String, String> data = idb.fetchRow(
            "SELECT * FROM partner WHERE pid = " + pid
        );

        if (data == null) return;

        jTextField1.setText(data.get("pid"));
        jTextField2.setText(data.get("namn"));
        jTextField3.setText(data.get("kontaktperson"));
        jTextField4.setText(data.get("kontaktepost"));
        jTextField5.setText(data.get("telefon"));
        jTextField6.setText(data.get("adress"));
        jTextField7.setText(data.get("branch"));

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Fel vid hämtning av partner");
    }
        
        
    }//GEN-LAST:event_PartnersActionPerformed

    private void GåTillbakaKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GåTillbakaKnappActionPerformed
        // TODO add your handling code here:
        
         this.setVisible(false);
        this.dispose();
        
         new Meny(idb,inloggadAnvandare,isAdmin).setVisible(true);
    }//GEN-LAST:event_GåTillbakaKnappActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // TODO add your handling code here:
        
         if (!isAdmin) {
        JOptionPane.showMessageDialog(this, "Du saknar behörighet.");
        return;
    }

    try {
        String pid = jTextField1.getText();
        String namn = jTextField2.getText();
        String kontaktperson = jTextField3.getText();
        String kontaktepost = jTextField4.getText();
        String telefon = jTextField5.getText();
        String adress = jTextField6.getText();
        String branch = jTextField7.getText();

        String sql =
            "UPDATE partner SET " +
            "namn = '" + namn + "', " +
            "kontaktperson = '" + kontaktperson + "', " +
            "kontaktepost = '" + kontaktepost + "', " +
            "telefon = '" + telefon + "', " +
            "adress = '" + adress + "', " +
            "branch = '" + branch + "' " +
            "WHERE pid = " + pid;

        idb.update(sql);

        JOptionPane.showMessageDialog(this, "Partner uppdaterad!");
        
        setFieldsEditable(false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Fel vid sparande: " + e.getMessage());
    }
        
        
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnÄndraUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraUppgifterActionPerformed
        // TODO add your handling code here:
        
        setFieldsEditable(true);
        
    }//GEN-LAST:event_btnÄndraUppgifterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new hanteraPartner().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adress;
    private javax.swing.JLabel Bransch;
    private javax.swing.JButton GåTillbakaKnapp;
    private javax.swing.JLabel KontaktEpost;
    private javax.swing.JLabel KontaktPerson;
    private javax.swing.JLabel Namn;
    private javax.swing.JLabel PartnerID;
    private javax.swing.JComboBox<String> Partners;
    private javax.swing.JLabel Telefon;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnÄndraUppgifter;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    private void loadPartnerData() {
        
       try {
       Partners.removeAllItems();

        var lista = idb.fetchColumn(
            "SELECT CONCAT(pid, ' - ', namn) FROM partner ORDER BY namn"
        );

        for (String rad : lista) {
            Partners.addItem(rad);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Kunde inte hämta partners");
    }
}  
    
    private void setFieldsEditable(boolean editable) {
        
        jTextField1.setEditable(false);
        jTextField2.setEditable(editable);
        jTextField3.setEditable(editable);
        jTextField4.setEditable(editable);
        jTextField5.setEditable(editable);
        jTextField6.setEditable(editable);
        jTextField7.setEditable(editable);

    }
    
        
}
