/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SDGSweden2025;

import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfException;
import java.util.ArrayList;

/**
 *
 * @author chris
 */
public class HanteraLand extends javax.swing.JPanel {

    private String inloggadAnvandare;
    private boolean isAdmin;
    private InfDB idb;
    private boolean laggTillLage = false;

    /**
     * Creates new form HanteraLand
     */
    public HanteraLand(String inloggadAnvandare, boolean isAdmin, InfDB idb) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.isAdmin = isAdmin;
        initComponents();
        fyllLandCombo();
        setLandIdEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("LandID");

        jLabel2.setText("Namn");

        jLabel3.setText("Språk");

        jLabel4.setText("Valuta");

        jLabel5.setText("Tidszon");

        jLabel6.setText("Politisk struktur");

        jLabel7.setText("Ekonomi");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jTextField3.setText("jTextField3");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jTextField4.setText("jTextField4");
        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jTextField5.setText("jTextField5");
        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        jTextField6.setText("jTextField6");
        jTextField6.addActionListener(this::jTextField6ActionPerformed);

        jTextField7.setText("jTextField7");
        jTextField7.addActionListener(this::jTextField7ActionPerformed);

        jButton1.setText("");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jButton2.setText("Spara");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Lägg till Land");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7});

    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            String vald = (String) jComboBox1.getSelectedItem();
            if (vald == null) {
                return;
            }
            if (!vald.contains(" - ")) {
                return;
            }

            String lid = vald.split(" - ")[0].trim();

            HashMap<String, String> data = idb.fetchRow(
                    "SELECT * FROM land WHERE lid = " + lid
            );

            if (data == null) {
                return;
            }

            jTextField1.setText(data.get("lid"));
            jTextField2.setText(data.get("namn"));
            jTextField3.setText(data.get("sprak"));
            jTextField4.setText(data.get("valuta"));
            jTextField5.setText(data.get("tidszon"));
            jTextField6.setText(data.get("politisk_struktur"));
            jTextField7.setText(data.get("ekonomi"));

            setLandIdEditable(false);
            laggTillLage = false;
            jButton3.setText("Lägg till Land");

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid hämtning av land");
            e.printStackTrace();
        }


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.Window w = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (w != null) {
            w.dispose();
        }

        new Meny(idb, inloggadAnvandare, isAdmin).setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String lid = jTextField1.getText().trim();
            String namn = jTextField2.getText().trim();
            String sprak = jTextField3.getText().trim();
            String valuta = jTextField4.getText().trim();
            String tidszon = jTextField5.getText().trim();
            String politisk = jTextField6.getText().trim();
            String ekonomi = jTextField7.getText().trim();

            if (lid.isEmpty() || namn.isEmpty()) {
                JOptionPane.showMessageDialog(this, "LandID och Namn måste vara ifyllda.");
                return;
            }

            String sql
                    = "UPDATE land SET "
                    + "namn = '" + namn + "', "
                    + "sprak = '" + sprak + "', "
                    + "valuta = '" + valuta + "', "
                    + "tidszon = '" + tidszon + "', "
                    + "politisk_struktur = '" + politisk + "', "
                    + "ekonomi = '" + ekonomi + "' "
                    + "WHERE lid = " + lid;

            idb.update(sql);
            JOptionPane.showMessageDialog(this, "Land uppdaterat!");

            fyllLandCombo();

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid sparande: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!isAdmin) {
            JOptionPane.showMessageDialog(this, "Du saknar behörighet.");
            return;
        }

        // STEG 1: gå in i "nytt land"-läge
        if (!laggTillLage) {
            nyttLandLage();
            laggTillLage = true;
            jButton3.setText("Spara nytt land"); // tydligt för användaren
            return;
        }

        // STEG 2: spara (INSERT)
        try {
            String lid = jTextField1.getText().trim();
            String namn = jTextField2.getText().trim();
            String sprak = jTextField3.getText().trim();
            String valuta = jTextField4.getText().trim();
            String tidszon = jTextField5.getText().trim();
            String politisk = jTextField6.getText().trim();
            String ekonomi = jTextField7.getText().trim();

            if (lid.isEmpty() || namn.isEmpty()) {
                JOptionPane.showMessageDialog(this, "LandID och Namn måste vara ifyllda.");
                return;
            }

            Integer.parseInt(lid);

            String finns = idb.fetchSingle("SELECT lid FROM land WHERE lid = " + lid);
            if (finns != null) {
                JOptionPane.showMessageDialog(this, "LandID finns redan.");
                return;
            }

            String sql
                    = "INSERT INTO land (lid, namn, sprak, valuta, tidszon, politisk_struktur, ekonomi) VALUES ("
                    + lid + ", '" + namn + "', '" + sprak + "', '" + valuta + "', '"
                    + tidszon + "', '" + politisk + "', '" + ekonomi + "')";

            idb.insert(sql);

            JOptionPane.showMessageDialog(this, "Land har lagts till!");

            // tillbaka till normalt läge
            laggTillLage = false;
            jButton3.setText("Lägg till Land");
            fyllLandCombo();

            // välj det nya landet automatiskt (valfritt men nice)
            jComboBox1.setSelectedItem(lid + " - " + namn);

            // lås landID igen
            setLandIdEditable(false);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "LandID måste vara ett heltal.");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid tillägg av land:\n" + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed
    private void loadLandById(String landId) {
        try {
            String sql = "SELECT lid, namn, sprak, valuta, tidszon, politisk_struktur, ekonomi "
                    + "FROM land WHERE lid = " + landId;

            HashMap<String, String> rad = idb.fetchRow(sql);

            if (rad == null) {
                JOptionPane.showMessageDialog(this, "Ingen rad hittades för lid=" + landId);
                return;
            }

            jTextField1.setText(rad.get("lid"));
            jTextField2.setText(rad.get("namn"));
            jTextField3.setText(rad.get("sprak"));
            jTextField4.setText(rad.get("valuta"));
            jTextField5.setText(rad.get("tidszon"));
            jTextField6.setText(rad.get("politisk_struktur"));
            jTextField7.setText(rad.get("ekonomi"));

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Databasfel: " + e.getMessage());
            e.printStackTrace();
        }

    }

    private void fyllLandCombo() {
        try {
            jComboBox1.removeAllItems();

            java.util.ArrayList<java.util.HashMap<String, String>> rows
                    = idb.fetchRows("SELECT lid, namn FROM land ORDER BY lid");

            if (rows == null || rows.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Inga länder hittades i tabellen land.");
                return;
            }

            for (java.util.HashMap<String, String> r : rows) {
                jComboBox1.addItem(r.get("lid") + " - " + r.get("namn"));
            }

        } catch (oru.inf.InfException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Fel vid laddning av länder: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void setLandIdEditable(boolean editable) {
        jTextField1.setEditable(editable);
        jTextField1.setEnabled(editable); // valfritt (gör det “grått” när låst)
    }

    private void nyttLandLage() {
        // töm alla fält
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");

        // nu ska LandID kunna skrivas
        setLandIdEditable(true);

        // sätt fokus i LandID
        jTextField1.requestFocus();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
