/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden2025;

import oru.inf.InfDB;

import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Ninee
 */
public class hanteraPartner extends javax.swing.JFrame {

    private String inloggadAnvandare;
    private boolean isAdmin;
    private InfDB idb;
    private boolean ignorePartnerComboEvent = false;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(hanteraPartner.class.getName());

    public hanteraPartner(InfDB idb, String inloggadAnvandare, boolean isAdmin) {

        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.isAdmin = isAdmin;

        initComponents();

        loadPartnerData();

        setFieldsEditable(false);

    }

    /**
     * Creates new form hanteraPartner
     */
    public hanteraPartner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PartnerID = new javax.swing.JLabel();
        Namn = new javax.swing.JLabel();
        KontaktPerson = new javax.swing.JLabel();
        KontaktEpost = new javax.swing.JLabel();
        Telefon = new javax.swing.JLabel();
        Adress = new javax.swing.JLabel();
        Bransch = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        GåTillbakaKnapp = new javax.swing.JButton();
        Partners = new javax.swing.JComboBox<>();
        btnSpara = new javax.swing.JButton();
        btnÄndraUppgifter = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        PartnerID.setText("PartnerID");

        Namn.setText("Namn");

        KontaktPerson.setText("Kontaktperson");

        KontaktEpost.setText("Kontaktepost");

        Telefon.setText("Telefon");

        Adress.setText("Adress");

        Bransch.setText("Bransch");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jTextField4.setText("jTextField4");
        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField6");

        jTextField7.setText("jTextField7");

        GåTillbakaKnapp.setText("");
        GåTillbakaKnapp.addActionListener(this::GåTillbakaKnappActionPerformed);

        Partners.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Partners.addActionListener(this::PartnersActionPerformed);

        btnSpara.setText("Spara");
        btnSpara.addActionListener(this::btnSparaActionPerformed);

        btnÄndraUppgifter.setText("Ändra uppgifter");
        btnÄndraUppgifter.addActionListener(this::btnÄndraUppgifterActionPerformed);

        jButton1.setText("Ta bort");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Lägg till");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Partners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GåTillbakaKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnÄndraUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnSpara))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Bransch)
                                            .addComponent(Telefon)
                                            .addComponent(Adress))
                                        .addGap(127, 127, 127)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(51, 51, 51)
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                                .addComponent(jButton2))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Namn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PartnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(115, 115, 115)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(KontaktPerson)
                                            .addComponent(KontaktEpost))
                                        .addGap(92, 92, 92)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(34, 34, 34)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Partners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GåTillbakaKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PartnerID)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Namn))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KontaktPerson)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KontaktEpost)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Telefon)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Adress)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bransch)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSpara)
                            .addComponent(btnÄndraUppgifter))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartnersActionPerformed
        // TODO add your handling code here:
        if (addingNewPartner || ignorePartnerComboEvent) {
            return;
        }

        setFieldsEditable(false);
        

        try {
            String vald = (String) Partners.getSelectedItem();
            if (vald == null) {
                return;
            }

            String pid = vald.split(" - ")[0];

            HashMap<String, String> data = idb.fetchRow(
                    "SELECT * FROM partner WHERE pid = " + pid
            );

            if (data == null) {
                return;
            }

            jTextField1.setText(data.get("pid"));
            jTextField2.setText(data.get("namn"));
            jTextField3.setText(data.get("kontaktperson"));
            jTextField4.setText(data.get("kontaktepost"));
            jTextField5.setText(data.get("telefon"));
            jTextField6.setText(data.get("adress"));
            jTextField7.setText(data.get("branch"));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fel vid hämtning av partner: " + e.getMessage());
        }


    }//GEN-LAST:event_PartnersActionPerformed

    private void GåTillbakaKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GåTillbakaKnappActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        this.dispose();

        new Meny(idb, inloggadAnvandare, isAdmin).setVisible(true);
    }//GEN-LAST:event_GåTillbakaKnappActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // TODO add your handling code here:
       String namn = jTextField2.getText();
String kontaktEpost = jTextField4.getText();
String telefon = jTextField5.getText();
if (Validator.isEmpty(namn)) {
    JOptionPane.showMessageDialog(this, "Partnernamn måste fyllas i.");
    return;
}

if (!Validator.isValidName(namn)) {
    JOptionPane.showMessageDialog(this, "Partnernamn är ogiltigt.");
    return;
}

if (Validator.isNotEmpty(kontaktEpost) && !Validator.isValidEmail(kontaktEpost)) {
    JOptionPane.showMessageDialog(this, "Ogiltig kontakt-e-post.");
    return;
}

if (!Validator.isValidOptionalPhone(telefon)) {
    JOptionPane.showMessageDialog(this, "Ogiltigt telefonnummer.");
    return;
}



        if (!isAdmin) {
            JOptionPane.showMessageDialog(this, "Du saknar behörighet.");
            return;
        }

        try {
            String pid = jTextField1.getText().trim();

            if (!pid.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "PartnerID är ogiltigt: " + pid);
                return;
            }

            String namnEsc = esc(namn);
            String kontaktperson = esc(jTextField3.getText());
            String kontaktepostEsc = esc(kontaktEpost);

            String telefonEsc = esc(telefon);

            String adress = esc(jTextField6.getText());
            String branch = esc(jTextField7.getText());

            if (namn.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Namn måste fyllas i.");
                return;
            }

            if (addingNewPartner) {
                String sql
                        = "INSERT INTO partner (pid, namn, kontaktperson, kontaktepost, telefon, adress, branch) VALUES ("
                        + pid + ", '" + namnEsc + "', '" + kontaktperson + "', '" + kontaktepostEsc + "', '" + telefonEsc + "', '" + adress + "', '" + branch + "')";


                JOptionPane.showMessageDialog(this, sql); // debug

                // VIKTIGT: INSERT ska köras med insert() om din InfDB har den metoden
                idb.insert(sql);

                JOptionPane.showMessageDialog(this, "Ny partner tillagd!");
                addingNewPartner = false;

           } else {

    String sql =
        "UPDATE partner SET " +
        "namn = '" + namnEsc + "', " +
        "kontaktperson = '" + kontaktperson + "', " +
        "kontaktepost = '" + kontaktepostEsc + "', " +
        "telefon = '" + telefonEsc + "', " +
        "adress = '" + adress + "', " +
        "branch = '" + branch + "' " +
        "WHERE pid = " + pid;

    JOptionPane.showMessageDialog(this, sql); // debug
    idb.update(sql);

    JOptionPane.showMessageDialog(this, "Partner uppdaterad!");
}


            setFieldsEditable(false);
            loadPartnerData();
            selectPartnerInCombo(pid);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fel vid sparande: " + e.getMessage());
        }

    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnÄndraUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraUppgifterActionPerformed
        // TODO add your handling code here:
        addingNewPartner = false;
        setFieldsEditable(true);

    }//GEN-LAST:event_btnÄndraUppgifterActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!isAdmin) {
            JOptionPane.showMessageDialog(this, "Du saknar behörighet.");
            return;
        }

        try {
            String pid = jTextField1.getText().trim();
            if (pid.isEmpty() || !pid.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Ingen giltig partner är vald.");
                return;
            }

            int svar = JOptionPane.showConfirmDialog(
                    this,
                    "Är du säker på att du vill ta bort partner med PID " + pid + "?",
                    "Bekräfta borttagning",
                    JOptionPane.YES_NO_OPTION
            );

            if (svar != JOptionPane.YES_OPTION) {
                return;
            }

            String sql = "DELETE FROM partner WHERE pid = " + pid;
            JOptionPane.showMessageDialog(this, sql); // debug, kan tas bort sen

            // VIKTIGT: DELETE ska köras med delete()
            idb.delete(sql);

            JOptionPane.showMessageDialog(this, "Partner borttagen!");

            addingNewPartner = false;
            setFieldsEditable(false);

            loadPartnerData();
            clearFields();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fel vid borttagning: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!isAdmin) {
            JOptionPane.showMessageDialog(this, "Du saknar behörighet.");
            return;
        }

        try {
            addingNewPartner = true;

            // Undvik att ActionPerformed triggas när vi ändrar comboboxen via kod
            ignorePartnerComboEvent = true;
            Partners.setSelectedItem(null);
            ignorePartnerComboEvent = false;

            clearFields();

            // Hämta nytt pid
            String maxPidStr = idb.fetchSingle("SELECT MAX(pid) FROM partner");
            int nextPid = 1;
            if (maxPidStr != null && !maxPidStr.equalsIgnoreCase("null") && !maxPidStr.isBlank()) {
                nextPid = Integer.parseInt(maxPidStr) + 1;
            }

            jTextField1.setText(String.valueOf(nextPid));

            setFieldsEditable(true);
            jTextField2.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fel vid Lägg till: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new hanteraPartner().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adress;
    private javax.swing.JLabel Bransch;
    private javax.swing.JButton GåTillbakaKnapp;
    private javax.swing.JLabel KontaktEpost;
    private javax.swing.JLabel KontaktPerson;
    private javax.swing.JLabel Namn;
    private javax.swing.JLabel PartnerID;
    private javax.swing.JComboBox<String> Partners;
    private javax.swing.JLabel Telefon;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnÄndraUppgifter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    private void loadPartnerData() {

        try {
            Partners.removeAllItems();

            var lista = idb.fetchColumn(
                    "SELECT CONCAT(pid, ' - ', namn) FROM partner ORDER BY namn"
            );

            for (String rad : lista) {
                Partners.addItem(rad);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Kunde inte hämta partners");
        }
    }

    private void setFieldsEditable(boolean editable) {

        jTextField1.setEditable(false);
        jTextField2.setEditable(editable);
        jTextField3.setEditable(editable);
        jTextField4.setEditable(editable);
        jTextField5.setEditable(editable);
        jTextField6.setEditable(editable);
        jTextField7.setEditable(editable);

    }

    private boolean addingNewPartner = false;

// En enkel escape för att inte krascha SQL om man skriver t.ex. O'Neill
    private String esc(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("'", "''").trim();
    }

    private void clearFields() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
    }

    private void selectPartnerInCombo(String pid) {
        for (int i = 0; i < Partners.getItemCount(); i++) {
            String item = Partners.getItemAt(i);
            if (item != null && item.startsWith(pid + " - ")) {
                Partners.setSelectedIndex(i);
                break;
            }
        }
    }
}
