/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden2025;

import oru.inf.InfDB;

/**
 *
 * @author Ninee
 */
public class hanteraAvdelning extends javax.swing.JFrame {

    private String inloggadAnvandare;
    private boolean isAdmin;
    private InfDB idb;
    private String avdid;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(hanteraAvdelning.class.getName());

    /**
     * Creates new form hanteraAvdelning
     */
    public hanteraAvdelning() {

        initComponents();
    }

    public hanteraAvdelning(InfDB idb, String inloggadAnvandare, boolean isAdmin) {

        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.isAdmin = isAdmin;

        initComponents();
        loadAvdelningData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfAvdelningsNamn = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        tfTelefon = new javax.swing.JTextField();
        tfStad = new javax.swing.JTextField();
        tfChef = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfAvdelningsID = new javax.swing.JTextField();
        ÄndraUppgifter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taBeskrivning = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();

        jLabel1.setText("Avdelningsnamn");

        jLabel2.setText("Beskrivning");

        jLabel3.setText("Adress");

        jLabel4.setText("Epost");

        jLabel5.setText("Telefon");

        jLabel6.setText("Stad");

        jLabel7.setText("ChefID");

        tfAvdelningsNamn.setText("jTextField1");
        tfAvdelningsNamn.addActionListener(this::tfAvdelningsNamnActionPerformed);

        tfAdress.setText("jTextField3");

        tfEpost.setText("jTextField4");

        tfTelefon.setText("jTextField5");

        tfStad.setText("jTextField6");
        tfStad.addActionListener(this::tfStadActionPerformed);

        tfChef.setText("jTextField7");

        jLabel8.setText("AvdelningsID");

        tfAvdelningsID.setText("jTextField8");
        tfAvdelningsID.addActionListener(this::tfAvdelningsIDActionPerformed);

        ÄndraUppgifter.setText("Spara");
        ÄndraUppgifter.addActionListener(this::ÄndraUppgifterActionPerformed);

        taBeskrivning.setColumns(20);
        taBeskrivning.setLineWrap(true);
        taBeskrivning.setRows(5);
        taBeskrivning.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taBeskrivning);

        jToggleButton1.setText("");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfChef, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfStad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ÄndraUppgifter)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(371, 371, 371))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfAvdelningsID)
                                .addComponent(tfEpost))
                            .addGap(17, 17, 17)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addComponent(tfAdress)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfAvdelningsNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, tfAvdelningsNamn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAvdelningsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAvdelningsNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfChef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ÄndraUppgifter)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ÄndraUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÄndraUppgifterActionPerformed
        // TODO add your handling code here:
        if (!isAdmin) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Du saknar behörighet att ändra avdelningen.");
            return;
        }

        // Extra skydd: ska aldrig vara null
        if (avdid == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingen avdelning är laddad.");
            return;
        }

        try {
            String namn = tfAvdelningsNamn.getText();
            String beskrivning = taBeskrivning.getText();
            String adress = tfAdress.getText();
            String epost = tfEpost.getText();
            String telefon = tfTelefon.getText();
            String stad = tfStad.getText();
            String chef = tfChef.getText();

            String sql
                    = "UPDATE avdelning SET "
                    + "namn = '" + namn + "', "
                    + "beskrivning = '" + beskrivning + "', "
                    + "adress = '" + adress + "', "
                    + "epost = '" + epost + "', "
                    + "telefon = '" + telefon + "', "
                    + "stad = '" + stad + "', "
                    + "chef = '" + chef + "' "
                    + "WHERE avdid = " + avdid;

            idb.update(sql);

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Avdelningen har sparats!");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Fel vid sparande av avdelning:\n" + e.getMessage());
        }


    }//GEN-LAST:event_ÄndraUppgifterActionPerformed

    private void tfAvdelningsIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAvdelningsIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAvdelningsIDActionPerformed

    private void tfAvdelningsNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAvdelningsNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAvdelningsNamnActionPerformed

    private void tfStadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStadActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        this.dispose();

        new Meny(idb, inloggadAnvandare, isAdmin).setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new hanteraAvdelning().setVisible(true));
    }

    private void loadAvdelningData() {
        try {
            // 1) Hämta aid (anställdID) via epost
            String aid = idb.fetchSingle(
                    "SELECT aid FROM anstalld WHERE epost = '" + inloggadAnvandare.trim() + "'"
            );

            if (aid == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Ingen anställd hittades med epost: " + inloggadAnvandare);
                return;
            }

            // 2) Hämta avdelningen  där denna person är chef
            var data = idb.fetchRow(
                    "SELECT a.avdid, a.namn, a.beskrivning, a.adress, a.epost, a.telefon, a.stad, a.chef "
                    + "FROM avdelning a "
                    + "JOIN anstalld an ON an.avdelning = a.avdid "
                    + "WHERE an.epost = '" + inloggadAnvandare.trim() + "'"
            );

            if (data == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Hittar ingen avdelning kopplad till denna admin.");
                return;
            }

            avdid = data.get("avdid");

            // 
            tfAvdelningsID.setText(avdid);
            tfAvdelningsNamn.setText(data.get("namn"));
            taBeskrivning.setText(data.get("beskrivning"));
            tfAdress.setText(data.get("adress"));
            tfEpost.setText(data.get("epost"));
            tfTelefon.setText(data.get("telefon"));
            tfStad.setText(data.get("stad"));
            tfChef.setText(data.get("chef"));

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Fel vid laddning av avdelning: " + e.getMessage());
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextArea taBeskrivning;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAvdelningsID;
    private javax.swing.JTextField tfAvdelningsNamn;
    private javax.swing.JTextField tfChef;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfStad;
    private javax.swing.JTextField tfTelefon;
    private javax.swing.JButton ÄndraUppgifter;
    // End of variables declaration//GEN-END:variables
}
