package SDGSweden2025;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author chris
 */

import oru.inf.InfDB;
import oru.inf.InfException;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.HashMap;

public class HanteraProjektPartner extends javax.swing.JFrame {
    private InfDB idb;
    private String epost;
    private boolean isAdmin;
    private int pid;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HanteraProjektPartner.class.getName());

    /**
     * Creates new form HanteraProjektPartner
     */
    public HanteraProjektPartner() {
        initComponents();
       
    }
    
    public HanteraProjektPartner(InfDB idb, String epost, boolean isAdmin, int pid) {
        this.idb = idb;
        this.epost = epost;
        this.isAdmin = isAdmin;
        this.pid = pid;

        initComponents();
        setLocationRelativeTo(null);

        
        loadAllaPartners();
        loadPartnersIProjekt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        cmbAllaPartners = new javax.swing.JComboBox<>();
        btnLaggTill = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnTaBort = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPartnersIProjekt = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lägg till partner:");

        cmbAllaPartners.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAllaPartners.addActionListener(this::cmbAllaPartnersActionPerformed);

        btnLaggTill.setText("Lägg till");
        btnLaggTill.addActionListener(this::btnLaggTillActionPerformed);

        jLabel2.setText("Partners i projektet:");

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(this::btnTaBortActionPerformed);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        listPartnersIProjekt.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listPartnersIProjekt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbAllaPartners, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLaggTill)
                            .addComponent(btnTaBort)
                            .addComponent(btnTillbaka))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbAllaPartners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaggTill))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTaBort)
                        .addGap(44, 44, 44)
                        .addComponent(btnTillbaka))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAllaPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAllaPartnersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAllaPartnersActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
  this.dispose();
    new Meny(idb, epost, isAdmin).setVisible(true);
    
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
  String vald = (String) cmbAllaPartners.getSelectedItem();

        if (vald == null || vald.equals("Välj partner")) {
            JOptionPane.showMessageDialog(this, "Välj en partner först");
            return;
        }

        String partnerPid = vald.split(" - ")[0].trim();

        try {
            // skydd mot dubletter
            String finns = idb.fetchSingle(
                "SELECT partner_pid FROM projekt_partner " +
                "WHERE pid = " + pid + " AND partner_pid = " + partnerPid
            );

            if (finns != null) {
                JOptionPane.showMessageDialog(this, "Partnern finns redan i projektet");
                return;
            }

            idb.insert(
                "INSERT INTO projekt_partner (pid, partner_pid) VALUES (" +
                pid + ", " + partnerPid + ")"
            );

            loadPartnersIProjekt();

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid tillägg: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLaggTillActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
    String vald = listPartnersIProjekt.getSelectedValue();

        if (vald == null) {
            JOptionPane.showMessageDialog(this, "Välj en partner att ta bort");
            return;
        }

        String partnerPid = vald.split(" - ")[0].trim();

        try {
            idb.delete(
                "DELETE FROM projekt_partner " +
                "WHERE pid = " + pid + " AND partner_pid = " + partnerPid
            );

            loadPartnersIProjekt();

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid borttagning: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HanteraProjektPartner().setVisible(true));
    }
private void loadAllaPartners() {
        try {
            cmbAllaPartners.removeAllItems();
            cmbAllaPartners.addItem("Välj partner");

            ArrayList<HashMap<String, String>> rows =
                idb.fetchRows("SELECT pid, namn FROM partner ORDER BY namn");

            if (rows != null) {
                for (HashMap<String, String> r : rows) {
                    cmbAllaPartners.addItem(r.get("pid") + " - " + r.get("namn"));
                }
            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Kunde inte hämta partners: " + e.getMessage());
        }
    }

    private void loadPartnersIProjekt() {
        DefaultListModel<String> model = new DefaultListModel<>();

        try {
            ArrayList<HashMap<String, String>> rows = idb.fetchRows(
                "SELECT p.pid, p.namn " +
                "FROM partner p " +
                "JOIN projekt_partner pp ON p.pid = pp.partner_pid " +
                "WHERE pp.pid = " + pid + " " +
                "ORDER BY p.namn"
            );

            if (rows != null) {
                for (HashMap<String, String> r : rows) {
                    model.addElement(r.get("pid") + " - " + r.get("namn"));
                }
            }

            listPartnersIProjekt.setModel(model);

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Kunde inte ladda projektets partners: " + e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cmbAllaPartners;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listPartnersIProjekt;
    // End of variables declaration//GEN-END:variables
}

