/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden2025;

import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author Bilda
 */
public class Meny extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;
    private boolean isAdmin;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Meny.class.getName());

    /**
     * Creates new form Meny
     */
    public Meny(InfDB idb, String inloggadAnvandare, boolean isAdmin) {
       this.idb = idb;
    this.inloggadAnvandare = inloggadAnvandare;
    this.isAdmin = isAdmin;

    initComponents();
    lblInloggadAnvandare.setText(inloggadAnvandare);

    // 🔐 HÄR styr du knappen
    KnappHanteraAvdelning.setVisible(isAdmin);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggadAnvandare = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        KnappAndraUppgifter = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblLoggaUt = new javax.swing.JButton();
        KnappHanteraAvdelning = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        KnappSePersonalPaAvdelning = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInloggadAnvandare.setText("Namn");

        jLabel1.setText("Inloggad:");

        KnappAndraUppgifter.setText("Se och Ändra Uppgifter");
        KnappAndraUppgifter.addActionListener(this::KnappAndraUppgifterActionPerformed);

        jButton2.setText("Mina Projekt");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        lblLoggaUt.setText("Logga ut");
        lblLoggaUt.addActionListener(this::lblLoggaUtActionPerformed);

        KnappHanteraAvdelning.setText("Se Avdelning");
        KnappHanteraAvdelning.addActionListener(this::KnappHanteraAvdelningActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Huvudmeny");

        KnappSePersonalPaAvdelning.setText("Personal (Avdelning)");
        KnappSePersonalPaAvdelning.addActionListener(this::KnappSePersonalPaAvdelningActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(130, 130, 130)
                        .addComponent(lblLoggaUt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(KnappSePersonalPaAvdelning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KnappAndraUppgifter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                        .addComponent(KnappHanteraAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblLoggaUt))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInloggadAnvandare)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KnappHanteraAvdelning)
                    .addComponent(KnappAndraUppgifter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KnappSePersonalPaAvdelning)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KnappAndraUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnappAndraUppgifterActionPerformed
     this.setVisible(false);
     new SeOchÄndraUppgifter(idb, inloggadAnvandare, isAdmin).setVisible(true);
    }//GEN-LAST:event_KnappAndraUppgifterActionPerformed

    private void lblLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLoggaUtActionPerformed
       this.setVisible(false);
       this.dispose();
       new Inloggningsfönster(idb).setVisible(true);
    }//GEN-LAST:event_lblLoggaUtActionPerformed

    private void KnappHanteraAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnappHanteraAvdelningActionPerformed
     if (!isAdmin) {
    javax.swing.JOptionPane.showMessageDialog(this, "Du saknar behörighet.");
    return;
     }
    }//GEN-LAST:event_KnappHanteraAvdelningActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void KnappSePersonalPaAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnappSePersonalPaAvdelningActionPerformed
        // TODO add your handling code here:
            this.setVisible(false);
            new SePersonal(idb, inloggadAnvandare, isAdmin).setVisible(true);
    }//GEN-LAST:event_KnappSePersonalPaAvdelningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                //new Meny().setVisible(true));
            }
        });
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KnappAndraUppgifter;
    private javax.swing.JButton KnappHanteraAvdelning;
    private javax.swing.JButton KnappSePersonalPaAvdelning;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JButton lblLoggaUt;
    // End of variables declaration//GEN-END:variables
}
