/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden2025;

import SDGSweden2025.Meny;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author ekrembethis
 */
public class MinaProjekt01 extends javax.swing.JFrame {
    
    private InfDB idb;
    private String epost;
    private boolean isAdmin;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MinaProjekt01.class.getName());

    /**
     * Creates new form MinaProjekt01
     */
    public MinaProjekt01(InfDB idb, String epost, boolean isAdmin) {
        this.idb = idb;
        this.epost = epost;
        this.isAdmin = isAdmin;

        initComponents();
        // Visa användarens e-postadress bredvid titeln
        lbltitlle.setText("<html><span style='color:black;'>Mina Projekt</span> " +
                      "<span style='color:gray;'>(" + epost + ")</span></html>");
        
        initTable();
        loadMinaProjekt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitlle = new javax.swing.JLabel();
        KnappGåTillbaka = new javax.swing.JButton();
        scrollMinaProjekt = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMinaProjekt = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitlle.setText("Mina Projekt");

        KnappGåTillbaka.setText("");
        KnappGåTillbaka.addActionListener(this::KnappGåTillbakaActionPerformed);

        tblMinaProjekt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMinaProjekt);

        scrollMinaProjekt.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollMinaProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbltitlle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KnappGåTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltitlle)
                    .addComponent(KnappGåTillbaka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollMinaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KnappGåTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnappGåTillbakaActionPerformed
        this.setVisible(false);
        this.dispose();
        new Meny(idb, epost, isAdmin).setVisible(true);;
    }//GEN-LAST:event_KnappGåTillbakaActionPerformed

    private void initTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Pid");
        model.addColumn("Projektnamn");
        model.addColumn("Beskrivning");
        model.addColumn("Startdatum");
        model.addColumn("Slutdatum");
        model.addColumn("Kostnad");
        model.addColumn("Status");
        model.addColumn("Prioritet");
        model.addColumn("Projektchef");
        model.addColumn("Land");

        tblMinaProjekt.setModel(model);
    }
    
    /**
         * Hämtar projekt som handläggaren är tilldelad till
     */
private void loadMinaProjekt() {
    DefaultTableModel model = (DefaultTableModel) tblMinaProjekt.getModel();
    model.setRowCount(0); // Rensa tabellen

    try {
        String sql =
            "SELECT p.pid, p.projektnamn, p.beskrivning, p.startdatum, p.slutdatum, " +
            "p.kostnad, p.status, p.prioritet, p.projektchef, p.land " +
            "FROM projekt p " +
            "JOIN ans_proj t ON p.pid = t.pid " +
            "JOIN anstalld a ON t.aid = a.aid " +
            "WHERE a.epost = '" + epost + "'";

        System.out.println("Executing query: " + sql); // 🔹 for debugging

        ArrayList<HashMap<String, String>> rows = idb.fetchRows(sql);

        if (rows != null) {
            for (HashMap<String, String> row : rows) {
                model.addRow(new Object[]{
                    row.get("pid"),
                    row.get("projektnamn"),
                    row.get("beskrivning"),
                    row.get("startdatum"),
                    row.get("slutdatum"),
                    row.get("kostnad"),
                    row.get("status"),
                    row.get("prioritet"),
                    row.get("projektchef"),
                    row.get("land")
                });
            }
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Fel vid hämtning av projekt: " + e.getMessage()
        );
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(() -> new MinaProjekt01().setVisible(true));*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KnappGåTillbaka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltitlle;
    private javax.swing.JScrollPane scrollMinaProjekt;
    private javax.swing.JTable tblMinaProjekt;
    // End of variables declaration//GEN-END:variables
}

//control
