/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden2025;

import SDGSweden2025.Meny;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

public class MinaProjekt01 extends javax.swing.JFrame {

    private InfDB idb;
    private String epost;
    private boolean isAdmin;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MinaProjekt01.class.getName());

    /**
     * Konstruktor som startar fönstret
     */
    public MinaProjekt01(InfDB idb, String epost, boolean isAdmin) {
        this.idb = idb;
        this.epost = epost;
        this.isAdmin = isAdmin;

        initComponents();
        // Visa användarens e-postadress bredvid titeln
        lbltitlle.setText("<html><span style='color:black;'>Mina Projekt</span> "
                + "<span style='color:gray;'>(" + epost + ")</span></html>");

        // Sätter val för status-filter
        cmbStatusAvdelning.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Alla", "Planerat", "Pågående", "Avslutat"}));

        // Initiera tabeller med kolumnnamn
        initTable();
        initAvdelningsTable();
        initPartnersTable();

        // Ladda data från databasen
        loadMinaProjekt();
        loadAvdelningsProjekt();
        loadPartnersUppgifter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitlle = new javax.swing.JLabel();
        KnappGåTillbaka = new javax.swing.JButton();
        scrollMinaProjekt = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMinaProjekt = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAvdelningsProjekt = new javax.swing.JTable();
        lbltitlle2 = new javax.swing.JLabel();
        cmbStatusAvdelning = new javax.swing.JComboBox<>();
        lblProjektsStatus = new javax.swing.JLabel();
        lblPartnersUppgifter = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPartnersUppgifter = new javax.swing.JTable();

        lbltitlle.setText("Mina Projekt");

        KnappGåTillbaka.setText("");
        KnappGåTillbaka.addActionListener(this::KnappGåTillbakaActionPerformed);

        tblMinaProjekt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMinaProjekt);

        scrollMinaProjekt.setViewportView(jScrollPane1);

        tblAvdelningsProjekt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAvdelningsProjekt);

        lbltitlle2.setText("Projekt på min avdelning");

        cmbStatusAvdelning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStatusAvdelning.addActionListener(this::cmbStatusAvdelningActionPerformed);

        lblProjektsStatus.setText("Status");

        lblPartnersUppgifter.setText("Partners uppgifter av mina projekt");

        tblPartnersUppgifter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblPartnersUppgifter);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltitlle2)
                        .addGap(193, 193, 193)
                        .addComponent(lblProjektsStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbStatusAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollMinaProjekt)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lbltitlle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(KnappGåTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPartnersUppgifter)
                                .addGap(0, 570, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltitlle)
                    .addComponent(KnappGåTillbaka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollMinaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltitlle2)
                    .addComponent(cmbStatusAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProjektsStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(lblPartnersUppgifter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KnappGåTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnappGåTillbakaActionPerformed
        this.setVisible(false);
        this.dispose();
        new Meny(idb, epost, isAdmin).setVisible(true);;
    }//GEN-LAST:event_KnappGåTillbakaActionPerformed

    private void cmbStatusAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusAvdelningActionPerformed
        // TODO add your handling code here:
        loadAvdelningsProjekt();
    }//GEN-LAST:event_cmbStatusAvdelningActionPerformed

    private void initTable() {
        // Initierar tabell för mina projekt med kolumner
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Pid");
        model.addColumn("Projektnamn");
        model.addColumn("Beskrivning");
        model.addColumn("Startdatum");
        model.addColumn("Slutdatum");
        model.addColumn("Kostnad");
        model.addColumn("Status");
        model.addColumn("Prioritet");
        model.addColumn("Projektchef");
        model.addColumn("Land");

        tblMinaProjekt.setModel(model);
    }

    private void initAvdelningsTable() {
        // Initierar tabell för avdelningens projekt med samma kolumner
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Pid");
        model.addColumn("Projektnamn");
        model.addColumn("Beskrivning");
        model.addColumn("Startdatum");
        model.addColumn("Slutdatum");
        model.addColumn("Kostnad");
        model.addColumn("Status");
        model.addColumn("Prioritet");
        model.addColumn("Projektchef");
        model.addColumn("Land");

        tblAvdelningsProjekt.setModel(model);
    }

    private void initPartnersTable() {
        // Initierar tabell för partners till projekten
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Pid");
        model.addColumn("Projektnamn");
        model.addColumn("Partner Namn");
        model.addColumn("Kontaktperson");
        model.addColumn("E-post");
        model.addColumn("Telefon");
        model.addColumn("Adress");
        model.addColumn("Bransch");
        model.addColumn("Stad");

        tblPartnersUppgifter.setModel(model);
    }

//Hämtar projekt som användaren är handläggare eller projektchef för  
    private void loadMinaProjekt() {
        DefaultTableModel model = (DefaultTableModel) tblMinaProjekt.getModel();
        model.setRowCount(0);

        try {
            // Hämta aid för inloggad användare
            String aidSql
                    = "SELECT aid FROM anstalld WHERE epost = '" + epost + "'";
            String aid = idb.fetchSingle(aidSql);

            // Hämta projekt där användaren är handläggare eller projektchef
            String sql
                    = "SELECT DISTINCT "
                    + "p.pid, p.projektnamn, p.beskrivning, p.startdatum, p.slutdatum, "
                    + "p.kostnad, p.status, p.prioritet, p.projektchef, p.land "
                    + "FROM projekt p "
                    + "LEFT JOIN ans_proj ap ON p.pid = ap.pid "
                    + "WHERE ap.aid = " + aid + " "
                    + "OR p.projektchef = " + aid;

            System.out.println("Executing MinaProjekt-SQL:\n" + sql);

            ArrayList<HashMap<String, String>> rows = idb.fetchRows(sql);

            if (rows != null) {
                for (HashMap<String, String> row : rows) {
                    // Lägg till varje projekt i tabellen
                    model.addRow(new Object[]{
                        row.get("pid"),
                        row.get("projektnamn"),
                        row.get("beskrivning"),
                        row.get("startdatum"),
                        row.get("slutdatum"),
                        row.get("kostnad"),
                        row.get("status"),
                        row.get("prioritet"),
                        row.get("projektchef"),
                        row.get("land")
                    });
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Fel vid hämtning av projekt: " + e.getMessage()
            );
        }
    }
//Hämtar projekt för användarens avdelning

    private void loadAvdelningsProjekt() {
        DefaultTableModel model
                = (DefaultTableModel) tblAvdelningsProjekt.getModel();
        model.setRowCount(0);

        try {
            // Hämta avdelning för inloggad användare
            String avdelningSql
                    = "SELECT avdelning FROM anstalld WHERE epost = '" + epost + "'";
            String avdelning = idb.fetchSingle(avdelningSql);

            // Statusfilter från ComboBox
            String valdStatus = cmbStatusAvdelning.getSelectedItem().toString();

            // Hämta projekt för avdelningen
            String sql
                    = "SELECT DISTINCT "
                    + "p.pid, p.projektnamn, p.beskrivning, p.startdatum, p.slutdatum, "
                    + "p.kostnad, p.status, p.prioritet, p.projektchef, p.land "
                    + "FROM projekt p "
                    + "JOIN ans_proj ap ON p.pid = ap.pid "
                    + "JOIN anstalld a ON ap.aid = a.aid "
                    + "WHERE a.avdelning = " + avdelning + " ";

            System.out.println("Executing avdelnings-SQL:\n" + sql);

            // Lägg till statusfilter om det inte är "Alla"
            if (!valdStatus.equals("Alla")) {
                sql += "AND p.status = '" + valdStatus + "' ";
            }

            var rows = idb.fetchRows(sql);

            if (rows != null) {
                for (var row : rows) {
                    model.addRow(new Object[]{
                        row.get("pid"),
                        row.get("projektnamn"),
                        row.get("beskrivning"),
                        row.get("startdatum"),
                        row.get("slutdatum"),
                        row.get("kostnad"),
                        row.get("status"),
                        row.get("prioritet"),
                        row.get("projektchef"),
                        row.get("land")
                    });
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Fel vid hämtning av avdelningens projekt: " + e.getMessage()
            );
        }
    }

//Hämtar partners för alla projekt som användaren är ansvarig för
    private void loadPartnersUppgifter() {

        DefaultTableModel model
                = (DefaultTableModel) tblPartnersUppgifter.getModel();
        model.setRowCount(0); // Clear table

        try {
            // Hämta aid för inloggad användare
            String aidSql
                    = "SELECT aid FROM anstalld WHERE epost = '" + epost + "'";
            String aid = idb.fetchSingle(aidSql);

            // Hämta alla projekt där användaren är handläggare eller projektchef
            String projektSql
                    = "SELECT DISTINCT p.pid, p.projektnamn "
                    + "FROM projekt p "
                    + "LEFT JOIN ans_proj ap ON p.pid = ap.pid "
                    + "WHERE ap.aid = " + aid + " "
                    + "OR p.projektchef = " + aid;

            System.out.println("Executing partner-projekt SQL:\n" + projektSql);

            ArrayList<HashMap<String, String>> projektRows
                    = idb.fetchRows(projektSql);

            if (projektRows != null) {
                for (HashMap<String, String> projekt : projektRows) {

                    String pid = projekt.get("pid");
                    String projektnamn = projekt.get("projektnamn");

                    // Hämta partners för projektet
                    String partnerSql
                            = "SELECT "
                            + "pa.namn, "
                            + "pa.kontaktperson, "
                            + "pa.kontaktepost, "
                            + "pa.telefon, "
                            + "pa.adress, "
                            + "pa.branch, "
                            + "stad_tab.stadnamn "
                            + "FROM partner pa "
                            + "JOIN projekt_partner pp ON pa.pid = pp.partner_pid "
                            + "LEFT JOIN ( "
                            + "    SELECT sid, namn AS stadnamn FROM stad "
                            + ") stad_tab ON pa.stad = stad_tab.sid "
                            + "WHERE pp.pid = " + pid;

                    ArrayList<HashMap<String, String>> partnerRows
                            = idb.fetchRows(partnerSql);

                    if (partnerRows != null) {
                        for (HashMap<String, String> partner : partnerRows) {
                            // Lägg till varje partner i tabellen
                            model.addRow(new Object[]{
                                pid,
                                projektnamn,
                                partner.get("namn"),
                                partner.get("kontaktperson"),
                                partner.get("kontaktepost"),
                                partner.get("telefon"),
                                partner.get("adress"),
                                partner.get("branch"),
                                partner.get("stadnamn")
                            });
                        }
                    }
                }
            }

        } catch (InfException e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Fel vid hämtning av partners: " + e.getMessage()
            );
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(() -> new MinaProjekt01().setVisible(true));*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KnappGåTillbaka;
    private javax.swing.JComboBox<String> cmbStatusAvdelning;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPartnersUppgifter;
    private javax.swing.JLabel lblProjektsStatus;
    private javax.swing.JLabel lbltitlle;
    private javax.swing.JLabel lbltitlle2;
    private javax.swing.JScrollPane scrollMinaProjekt;
    private javax.swing.JTable tblAvdelningsProjekt;
    private javax.swing.JTable tblMinaProjekt;
    private javax.swing.JTable tblPartnersUppgifter;
    // End of variables declaration//GEN-END:variables
}
