/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SDGSweden2025;

import oru.inf.InfDB;
/**
 *
 * @author Bilda
 */
public class SeOchÄndraUppgifter extends javax.swing.JFrame {
    
    private InfDB idb;
    private String epost;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SeOchÄndraUppgifter.class.getName());

    /**
     * Creates new form SeOchÄndraUppgifter
     */
    public SeOchÄndraUppgifter(InfDB idb, String epost) {
    this.idb = idb;
    this.epost = epost;
    initComponents();
    loadUserData();
    KnappSparaAndring.addActionListener(this::KnappSparaAndringActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        lblSeMinaUppgifter = new javax.swing.JLabel();
        KnappSparaAndring = new javax.swing.JButton();
        KnappGåTillbaka = new javax.swing.JButton();
        RadFornamn = new javax.swing.JLabel();
        tfAdress = new javax.swing.JTextField();
        RadEfternamn = new javax.swing.JLabel();
        RadAdress = new javax.swing.JLabel();
        RadTelefon = new javax.swing.JLabel();
        tfTelefon = new javax.swing.JTextField();
        RadEpost = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFornamn = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        RadPersonalID = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSeMinaUppgifter.setText("Mina Uppgifter:");

        KnappSparaAndring.setText("Spara");
        KnappSparaAndring.addActionListener(this::KnappSparaAndringActionPerformed);

        KnappGåTillbaka.setText("");
        KnappGåTillbaka.addActionListener(this::KnappGåTillbakaActionPerformed);

        RadFornamn.setText("Förnamn:");

        tfAdress.setEditable(false);

        RadEfternamn.setText("Efternamn:");

        RadAdress.setText("Adress:");

        RadTelefon.setText("Telefon:");

        RadEpost.setText("E-post:");

        lblFornamn.setText("jLabel7");

        lblEpost.setText("jLabel1");

        lblEfternamn.setText("jLabel2");

        lblID.setText("jLabel3");

        RadPersonalID.setText("Personal-ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lblSeMinaUppgifter))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadFornamn)
                            .addComponent(RadEfternamn)
                            .addComponent(RadAdress)
                            .addComponent(RadTelefon)
                            .addComponent(RadEpost))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFornamn)
                                    .addComponent(lblEpost)
                                    .addComponent(lblEfternamn))
                                .addGap(393, 393, 393)
                                .addComponent(jLabel6))
                            .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RadPersonalID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KnappGåTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KnappSparaAndring))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeMinaUppgifter)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KnappGåTillbaka)
                    .addComponent(lblID)
                    .addComponent(RadPersonalID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadFornamn)
                    .addComponent(lblFornamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadEfternamn)
                    .addComponent(lblEfternamn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KnappSparaAndring))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadEpost)
                            .addComponent(lblEpost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadAdress)
                            .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadTelefon)
                            .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KnappGåTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnappGåTillbakaActionPerformed
        this.setVisible(false);
        this.dispose();
        new Meny(idb, epost).setVisible(true);
    }//GEN-LAST:event_KnappGåTillbakaActionPerformed

    private void KnappSparaAndringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnappSparaAndringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KnappSparaAndringActionPerformed

    private void loadUserData() {
    try {
        String query = "SELECT aid, fornamn, efternamn, adress, telefon, epost " +
                       "FROM anstalld WHERE epost = '" + epost + "'";
        var data = idb.fetchRow(query);
        System.out.println("E-post som skickas: " + epost);
        System.out.println("Data från DB: " + data);
        if (data != null) {
            lblID.setText(data.get("aid") != null ? String.valueOf(data.get("aid")) : "");
            lblFornamn.setText(data.get("fornamn") != null ? data.get("fornamn") : "");
            lblEfternamn.setText(data.get("efternamn") != null ? data.get("efternamn") : "");
            lblEpost.setText(data.get("epost") != null ? data.get("epost") : "");
            tfAdress.setText(data.get("adress") != null ? data.get("adress") : "");
            tfTelefon.setText(data.get("telefon") != null ? data.get("telefon") : "");

            // Make editable fields editable
            tfAdress.setEditable(true);
            tfTelefon.setEditable(true);

            // Disable labels
            lblID.setEnabled(false);
            lblFornamn.setEnabled(false);
            lblEfternamn.setEnabled(false);
            lblEpost.setEnabled(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingen användare hittades med e-post: " + epost);
        }
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fel vid uppdatering: " + ex.getMessage());
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KnappGåTillbaka;
    private javax.swing.JButton KnappSparaAndring;
    private javax.swing.JLabel RadAdress;
    private javax.swing.JLabel RadEfternamn;
    private javax.swing.JLabel RadEpost;
    private javax.swing.JLabel RadFornamn;
    private javax.swing.JLabel RadPersonalID;
    private javax.swing.JLabel RadTelefon;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblSeMinaUppgifter;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}

//Hej
// Hejdå!
//hALLÅ ALLA:::
//Test 1
//Test 2
//test 3 Ekrem
// Test 4 Jamal