/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package SDGSweden2025;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;


/**
 *
 * @author Ninee
 */
public class TaBortAnstalld extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TaBortAnstalld.class.getName());

    
    private InfDB idb;
    private String inloggadAnvandare;
    private boolean isAdmin;
    
    // sparar AID som hittades via sökningen personen gjorde
    
    private Integer hittaAid=null;     
    
   
    
    /**
     * Creates new form TaBortAnstalld
     */
   public TaBortAnstalld (){
       
     initComponents();
    setLocationRelativeTo(null);
    
   }
           
           
    public TaBortAnstalld(InfDB idb, String inloggadAnvandare,boolean isAdmin ) {
       
        this.idb=idb;
        this.inloggadAnvandare=inloggadAnvandare;
        this.isAdmin=isAdmin;
        
        
        initComponents();
        setLocationRelativeTo(null);
        
        // åtkomstkontroll endast admin får använda
        
        if(!isAdmin){
            
            JOptionPane.showMessageDialog(this, "Du saknar behörighet att ta bort anställda");
            
            tillbakaTillMeny();
        }
        
        
        tfSok.setText("");
        jTextArea1.setText("");
        btnTaBort.setEnabled(false);   // man får inte ta bort en anställd innan man har sökt fram någon
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KnappGåTillbaka = new javax.swing.JButton();
        lblTitel = new javax.swing.JLabel();
        lblSok = new javax.swing.JLabel();
        tfSok = new javax.swing.JTextField();
        btnSok = new javax.swing.JButton();
        lblInfoTitel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnTaBort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KnappGåTillbaka.setText("");
        KnappGåTillbaka.addActionListener(this::KnappGåTillbakaActionPerformed);

        lblTitel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitel.setText("Ta bort anställd");

        lblSok.setText("AnställningsID");

        btnSok.setText("Sök");
        btnSok.addActionListener(this::btnSokActionPerformed);

        lblInfoTitel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfoTitel.setText("Information");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        btnTaBort.setText("Ta bort anställd");
        btnTaBort.addActionListener(this::btnTaBortActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInfoTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitel, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(KnappGåTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfSok, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnSok)
                                .addContainerGap(92, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KnappGåTillbaka)
                    .addComponent(lblTitel))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSok)
                    .addComponent(tfSok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSok))
                .addGap(31, 31, 31)
                .addComponent(lblInfoTitel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnTaBort))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KnappGåTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnappGåTillbakaActionPerformed
       // Tillbaka knapp som skickar tillbaka användaren till Meny
       
       tillbakaTillMeny();
    }//GEN-LAST:event_KnappGåTillbakaActionPerformed

    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed
        // Söker efter den anställda
        
        
        jTextArea1.setText("");
        btnTaBort.setEnabled(false);
        hittaAid=null;
        
        String aidText=tfSok.getText().trim();
        
       if (Validator.isEmpty(aidText)) {
    JOptionPane.showMessageDialog(this, "Vänligen skriv in ett anställningsID (AID).");
    return;
}

if (!Validator.isPositiveInteger(aidText)) {
    JOptionPane.showMessageDialog(this, "AID måste vara ett positivt heltal.");
    return;
}

int aid = Integer.parseInt(aidText);


        
        try{
            
            // hämtar information om den anställda
            
           String sql= "SELECT aid, fornamn, efternamn, epost, avdelning FROM anstalld WHERE aid = " + aid;
              java.util.HashMap<String, String> rad = idb.fetchRow(sql);

        if (rad == null) {
            jTextArea1.setText("Ingen anställd hittades med AID: " + aid);
         
         return;
        }
        
        // Hämtar avdelningsnamn
        
        String avdid=rad.get("avdelning");
        
        String avdNamn= idb.fetchSingle("SELECT namn FROM avdelning WHERE avdid = " + avdid);
        if (avdNamn == null) avdNamn = "(okänd avdelning)";
        
        // Kollar vilken roll den anställda har (Admin,Handläggare eller om den endast är en vanlig anställd)
        
       String roll = "Anställd"; 
        String arAdmin = idb.fetchSingle("SELECT aid FROM admin WHERE aid = " + aid);
        String arHandlaggare = idb.fetchSingle("SELECT aid FROM handlaggare WHERE aid = " + aid);

        if (arAdmin != null) {
            roll = "Administratör";
        } else if (arHandlaggare != null) {
            roll = "Handläggare";
        }

            // Texten som visas
            
            String info= 
                    
             "AID:"  + rad.get("aid")+ "\n" + 
             "Roll: " + roll + "\n" +
             "Förnamn: " + rad.get("fornamn") + "\n" +
             "Efternamn: " + rad.get("efternamn") + "\n" +
             "E-post: " + rad.get("epost") + "\n" +
             "Avdelning: " + avdNamn + " (ID " + avdid + ")\n";  
            
            jTextArea1.setText(info);
            
            // spara den anställda som hittades så att ta bort knappen kan användas
            
            hittaAid=aid;
            
            btnTaBort.setEnabled(true);
            
        } catch (InfException e){
            
             JOptionPane.showMessageDialog(this, " Fel vid sökning: " + e.getMessage());
        }
       
    
         
    }//GEN-LAST:event_btnSokActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        // knapp som tar bort den anställda från systemet
        
        if (hittaAid == null) {
        JOptionPane.showMessageDialog(this, "Sök fram en anställd först.");
        return;
    }

    int aid = hittaAid;

    int svar = JOptionPane.showConfirmDialog(
            this,
            "Är du säker på att du vill ta bort anställd med AID: " + aid + "?",
            "Bekräfta borttagning",
            JOptionPane.YES_NO_OPTION
    );

    if (svar != JOptionPane.YES_OPTION) {
        return;
    }
    
     try {
        // Tar bort personens roller först 
        idb.delete("DELETE FROM admin WHERE aid = " + aid);
        idb.delete("DELETE FROM handlaggare WHERE aid = " + aid);

        // Sen ta bort personen från databasen (Sql)
        
        idb.delete("DELETE FROM anstalld WHERE aid = " + aid);

        JOptionPane.showMessageDialog(this, "Anställd borttagen.");

        // Rensar det som visas i fönstret efter borttagning
        
        hittaAid = null;
        tfSok.setText("");
        jTextArea1.setText("");
        btnTaBort.setEnabled(false);

    } catch (InfException e) {
        JOptionPane.showMessageDialog(this, "Kunde inte ta bort anställd: " + e.getMessage());
      }
        
    }//GEN-LAST:event_btnTaBortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TaBortAnstalld().setVisible(true));
    }
    
    
    private void tillbakaTillMeny(){
        
        if(idb != null && inloggadAnvandare != null){
            
            this.dispose();
            
            new Meny(idb, inloggadAnvandare, isAdmin).setVisible(true);
            
        } else {
            
            this.dispose();
        }
    }
    
   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KnappGåTillbaka;
    private javax.swing.JButton btnSok;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblInfoTitel;
    private javax.swing.JLabel lblSok;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JTextField tfSok;
    // End of variables declaration//GEN-END:variables
}
